# Generated by Django 4.1.7 on 2023-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='curso',
            field=models.ManyToManyField(to='AppCoder.curso'),
        ),
    ]
